name: Humble Semi Binary Main
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble
  schedule:
    - cron: '13 4 * * *'

jobs:
  humble_semi_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: humble
      ros_repo: main
      ref_for_scheduled_build: humble
      upstream_workspace: ur_simulation_gz.humble.repos
