name: Jazzy Binary Main
on:
  workflow_dispatch:
  pull_request:
    branches:
      - ros2
  push:
    branches:
      - ros2
  schedule:
    - cron: '13 4 * * *'

jobs:
  jazzy_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: jazzy
      ros_repo: main
      ref_for_scheduled_build: ros2
