name: Kilted Binary Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - ros2
  push:
    branches:
      - ros2
  schedule:
    - cron: '13 4 * * *'

jobs:
  kilted_binary_testing:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: kilted
      ros_repo: testing
      ref_for_scheduled_build: ros2
